apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kongfiles.developer.konghq.com
spec:
  group: developer.konghq.com
  names:
    kind: KongFile
    listKind: KongFileList
    plural: kongfiles
    singular: kongfile
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: KongFile is the Schema for the Kong files API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: KongFileSpec defines the desired state of KongFile
              properties:
                layout:
                  description: Layout to use for the file on the developer portal
                  type: string
                path:
                  description: Path for the file on the developer portal
                  type: string
                title:
                  description: Title of the file
                  type: string
                name:
                  description: Name of the file
                  type: string
                content:
                  description: Content of the file
                  type: string
                kind:
                  description: Kind of the file
                  type: string
                  enum:
                    - CONTENT
                    - SPECIFICATION
                    - ASSET
              type: object
            status:
              description: It defines the observed state of the KongFile
              properties:
                validated:
                  description: Status of the KongFile update
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: [ ]
  storedVersions: [ ]
